### ISSUE TITLE
net: switch only sends to 192.168.1.x subnet

### ISSUE THREAD

**Issue by clshortfuse** [WerWolv/SwitchXBOXController#2]
Looks like it sends sends to the broadcast ip of 192.168.1.x

https://github.com/WerWolv98/SwitchXBOXController/blob/e2a584becffa6089b4c186e21d4653e3123b750e/Switch_Client/source/main.c#L89

Usually, you can just freely send to 255.255.255.255, although I've seen some routers block this. Ideally, you'd want to get the subnet the Switch is connected to and transmit to its respective broadcast IP.

**Comment by WerWolv98** [comment]
Didn't know that, thanks!
Dynamically getting the broadcast IP is pretty hard on the switch since you can't directly access that data except using syscalls/calls to a sysmodule which hasn't been reversed yet.
I'm glad to change the IP to 255.255.255.255 though

**Comment by ValliantStorme** [comment]
It could be done so that the subnet is configurable using a config file, but I don't know if you'd want config file shenanigans

**Comment by sacredbanana** [comment]
I tested it by making it broadcast to 255.255.255.255 and it didn't work. Maybe my router blocked it. It works if I sent it to 10.0.1.255. When I say it works I mean it says it has successfully connected to my PC's IP address and the PC server says it has connected to the Switch's IP address.. but for some reason no key presses are being sent and so the controller isnt working at all beyond saying it has connected

**Comment by WerWolv** [comment]
Fixed in v1.2
