### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MexyACJ** [WerWolv/SwitchXBOXController#5]
How does someone use this.
Can someone give me some instructions to do this? I have the drive installed and have the switchXBOXcontroller server running on my pc and the client on my switch.

**Comment by EnterpriseFreak** [comment]
Does your ip address start with 192.168.1? If not you will have to build from source since the current release does not have the ability to broadcast to any ip address except for 192.168.1.255.

**Comment by WerWolv** [comment]
Should be fixed in v1.2
