### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by EnterpriseFreak** [WerWolv/SwitchXBOXController#6]
As you may remember i did some changes to the code about one month ago, however the lastest release of this project is still from before these changes where made. Since there currently is no relase with my changes users may still have trouble using this application when their router does not listen to broadcasts on 192.168.1.255.

**Comment by SamHep0803** [comment]
I +1 this, I can't get the thing to work using the release that the instructions tell us to. Not really a fan on compiling and running it on the switch.

**Comment by EnterpriseFreak** [comment]
Well since there is currently no new release with my changes i've compiled it for you: https://drive.google.com/open?id=1lfvBDUiDA7LD7t6VadVPIgcMjGVrazVb

**Comment by SamHep0803** [comment]
Thanks very much!

 Do you have a discord? I'm looking to make some HB apps but have no idea where to start.

**Comment by EnterpriseFreak** [comment]
Right now i dont have a discord but i could try to get one.

**Comment by SamHep0803** [comment]
Yes it's very easy, just go to discordapp,com

**Comment by EnterpriseFreak** [comment]
https://discord.gg/WQ8Gdf
There you go!

**Comment by WerWolv** [comment]
Finally got a new release out. Sorry about the long delay!
https://github.com/WerWolv/SwitchXBOXController/releases/tag/v1.2
